config/routes.rb
Rails.application.routes.draw do
  resources :loads do
    resources :orders do
      delete 'unassign' => 'orders#unassign'
      post 'assign' => 'orders#assign'
    end
    get 'edit_orders' => 'loads#edit_orders'
    get 'download' => 'loads#download'
  end
  resources :addresses
  resources :drivers
  resources :vehicles

  post 'upload_orders' => 'loads#upload_orders'

  #get '/load/:id/orders/assign' => 'orders#assign'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/load.rb
class Load < ApplicationRecord
  has_many :orders
  belongs_to :driver
end

app/controllers/loads_controller.rb
class LoadsController < ApplicationController
  before_action :set_load, only: [:show, :edit, :update, :destroy]

  # GET /loads
  # GET /loads.json
  def index
    @loads = Load.all
  end

  # GET /loads/1
  # GET /loads/1.json
  def show
  end

  # GET /loads/new
  def new
    @load = Load.new
  end

  # GET /loads/1/edit
  def edit
  end

  # POST /loads
  # POST /loads.json
  def create
    @load = Load.new(load_params)

    respond_to do |format|
      if @load.save
        format.html { redirect_to @load, notice: 'Load was successfully created.' }
        format.json { render :show, status: :created, location: @load }
      else
        format.html { render :new }
        format.json { render json: @load.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loads/1
  # PATCH/PUT /loads/1.json
  def update
    respond_to do |format|
      if @load.update(load_params)
        format.html { redirect_to @load, notice: 'Load was successfully updated.' }
        format.json { render :show, status: :ok, location: @load }
      else
        format.html { render :edit }
        format.json { render json: @load.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loads/1
  # DELETE /loads/1.json
  def destroy
    @load.destroy
    respond_to do |format|
      format.html { redirect_to loads_url, notice: 'Load was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def edit_orders
    @assignOrders = Order.where(load_id: params[:load_id])
    @unassignOrders = Order.where(load_id: nil)
    @load = Load.find(params[:load_id])
  end

  def download

  end

  def upload_orders
    require 'csv'

    csv_text = params[ :csv_file ].tempfile.read
    csv = CSV.parse(csv_text, :headers => true)
    csv.each do |row|
      params = row.to_hash
      originAddress = params.slice(:origin_raw_line_1, :origin_city, :origin_state, :origin_zip, :origin_country)
      destinationAddress = params.slice(:destination_raw_line_1, :destination_city, :destination_state, :destination_zip, :destination_country)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_load
      @load = Load.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def load_params
      params.require(:load).permit(:deliveryDate, :deliveryShift, :driver_id)
    end
end

app/helpers/loads_helper.rb
module LoadsHelper
end

app/views/loads/_form.html.erb
<%= form_for(load) do |f| %>
  <% if load.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(load.errors.count, "error") %> prohibited this load from being saved:</h2>

      <ul>
      <% load.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :deliveryDate %>
    <%= f.date_select :deliveryDate %>
  </div>

  <div class="field">
    <%= f.label :deliveryShift %>
    <%= f.text_field :deliveryShift %>
  </div>

  <div class="field">
    <%= f.label :driver_id %>
    <%= f.text_field :driver_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/loads/edit.html.erb
<h1>Editing Load</h1>

<%= render 'form', load: @load %>

<%= link_to 'Show', @load %> |
<%= link_to 'Back', loads_path %>

app/views/loads/edit_orders.html.erb
<h1>Assigned orders</h1>

<table>
  <tr>
    <th>Deliverydate</th>
    <th>Deliveryshift</th>
    <th>Originname</th>
    <th>Originaddress</th>
    <th>Clientname</th>
    <th>Destinationaddress</th>
    <th>Phonenumber</th>
    <th>Mode</th>
    <th>Purchaseordernumber</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @assignOrders.each do |order| %>
      <tr>
        <td><%= order.deliveryDate %></td>
        <td><%= order.deliveryShift %></td>
        <td><%= order.originName %></td>
        <td><%= order.origin_address_id %></td>
        <td><%= order.clientName %></td>
        <td><%= order.destination_address_id %></td>
        <td><%= order.phoneNumber %></td>
        <td><%= order.mode %></td>
        <td><%= order.purchaseOrderNumber %></td>
        <td><%= link_to 'Show', [order.load, order] %></td>
        <td><%= link_to 'Edit', edit_load_order_path(order.load, order) %></td>
        <td><%= link_to 'Unassign', load_order_unassign_path(order.load, order), :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
  <% end %>
</table>

<br />

<h1>Unassigned orders</h1>

<table>
  <tr>
    <th>Deliverydate</th>
    <th>Deliveryshift</th>
    <th>Originname</th>
    <th>Originaddress</th>
    <th>Clientname</th>
    <th>Destinationaddress</th>
    <th>Phonenumber</th>
    <th>Mode</th>
    <th>Purchaseordernumber</th>
    <th>Volume</th>
    <th>Handlingunitquantity</th>
    <th>Handlingunittype</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @unassignOrders.each do |order| %>
      <tr>
        <td><%= order.deliveryDate %></td>
        <td><%= order.deliveryShift %></td>
        <td><%= order.originName %></td>
        <td><%= order.origin_address_id %></td>
        <td><%= order.clientName %></td>
        <td><%= order.destination_address_id %></td>
        <td><%= order.phoneNumber %></td>
        <td><%= order.mode %></td>
        <td><%= order.purchaseOrderNumber %></td>
        <td><%= order.volume %></td>
        <td><%= order.handlingUnitQuantity %></td>
        <td><%= order.handlingUnitType %></td>
        <td><%= link_to 'Show', [@load, order] %></td>
        <td><%= link_to 'Edit', edit_load_order_path(@load, order) %></td>
        <td><%= link_to 'Assign', load_order_assign_path(@load, order), :method => :post %></td>
      </tr>
  <% end %>
</table>

<br />
<%= link_to 'Back', loads_path %>

app/views/loads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Loads</h1>

<table>
  <thead>
    <tr>
      <th>Deliverydate</th>
      <th>Deliveryshift</th>
      <th>Driver</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @loads.each do |load| %>
      <tr>
        <td><%= load.deliveryDate %></td>
        <td><%= load.deliveryShift %></td>
        <td><%= load.driver %></td>
        <td><%= link_to 'Edit Orders', load_edit_orders_path(load) %></td>
        <td><%= link_to 'Download', load_download_path(load) %></td>
        <td><%= link_to 'Show', load %></td>
        <td><%= link_to 'Edit', edit_load_path(load) %></td>
        <td><%= link_to 'Destroy', load, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Load', new_load_path %>
<%= form_tag(upload_orders_path, :method => 'post', multipart: true) do %>
    <%= file_field_tag 'csv_file', accept: 'text/csv' %>
    <%= submit_tag 'Submit' %>
<% end %>

app/views/loads/new.html.erb
<h1>New Load</h1>

<%= render 'form', load: @load %>

<%= link_to 'Back', loads_path %>

app/views/loads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Deliverydate:</strong>
  <%= @load.deliveryDate %>
</p>

<p>
  <strong>Deliveryshift:</strong>
  <%= @load.deliveryShift %>
</p>

<p>
  <strong>Driver:</strong>
  <%= @load.driver %>
</p>

<%= link_to 'Edit', edit_load_path(@load) %> |
<%= link_to 'Back', loads_path %>