config/routes.rb
Rails.application.routes.draw do
  resources :loads do
    resources :orders do
      delete 'unassign' => 'orders#unassign'
      post 'assign' => 'orders#assign'
    end
    get 'edit_orders' => 'loads#edit_orders'
    get 'download' => 'loads#download'
  end
  resources :addresses
  resources :drivers
  resources :vehicles

  post 'upload_orders' => 'loads#upload_orders'

  #get '/load/:id/orders/assign' => 'orders#assign'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :load
  #belongs_to :origin_address_id, class_name: 'Address'
  #belongs_to :destination_address_id, class_name: 'Address'
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_orders
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET loads/1/orders
  def index
    @orders = @load.orders
  end

  # GET loads/1/orders/1
  def show
  end

  # GET loads/1/orders/new
  def new
    @order = @load.orders.build
  end

  # GET loads/1/orders/1/edit
  def edit
  end

  # POST loads/1/orders
  def create
    @order = @load.orders.build(order_params)

    if @order.save
      redirect_to([@order.load, @order], notice: 'Order was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT loads/1/orders/1
  def update
    if @order.update_attributes(order_params)
      redirect_to([@order.load, @order], notice: 'Order was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE loads/1/orders/1
  def destroy
    @order.destroy

    redirect_to load_orders_url(@load)
  end

  def unassign
    @order = @load.orders.find(params[:order_id])
    @order.update_attributes({load_id: nil})

    redirect_to load_edit_orders_path(@load)
  end

  def assign
    @order = Order.find(params[:order_id])
    @order.update_attributes({load_id: params[:load_id]})

    redirect_to load_edit_orders_path(@load)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orders
      @load = Load.find(params[:load_id])
    end

    def set_order
      @order = @load.orders.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def order_params
      params.require(:order).permit(:deliveryDate, :deliveryShift, :originName, :origin_address_id, :clientName, :destination_address_id, :phoneNumber, :mode, :purchaseOrderNumber, :volume, :handlingUnitQuantity, :handlingUnitType)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for([@order.load, @order]) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :deliveryDate %><br />
    <%= f.date_select :deliveryDate %>
  </div>
  <div class="field">
    <%= f.label :deliveryShift %><br />
    <%= f.text_field :deliveryShift %>
  </div>
  <div class="field">
    <%= f.label :originName %><br />
    <%= f.text_field :originName %>
  </div>
  <div class="field">
    <%= f.label :origin_address_id %><br />
    <%= f.collection_select :origin_address_id, Address.all, :id, :rawLine1 %>
  </div>
  <div class="field">
    <%= f.label :clientName %><br />
    <%= f.text_field :clientName %>
  </div>
  <div class="field">
    <%= f.label :destination_address_id %><br />
    <%= f.collection_select :destination_address_id, Address.all, :id, :rawLine1 %>
  </div>
  <div class="field">
    <%= f.label :phoneNumber %><br />
    <%= f.text_field :phoneNumber %>
  </div>
  <div class="field">
    <%= f.label :mode %><br />
    <%= f.text_field :mode %>
  </div>
  <div class="field">
    <%= f.label :purchaseOrderNumber %><br />
    <%= f.number_field :purchaseOrderNumber %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', [@order.load, @order] %> |
<%= link_to 'Back', load_orders_path(@order.load) %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <tr>
    <th>Deliverydate</th>
    <th>Deliveryshift</th>
    <th>Originname</th>
    <th>Originaddress</th>
    <th>Clientname</th>
    <th>Destinationaddress</th>
    <th>Phonenumber</th>
    <th>Mode</th>
    <th>Purchaseordernumber</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.deliveryDate %></td>
    <td><%= order.deliveryShift %></td>
    <td><%= order.originName %></td>
    <td><%= order.origin_address_id %></td>
    <td><%= order.clientName %></td>
    <td><%= order.destination_address_id %></td>
    <td><%= order.phoneNumber %></td>
    <td><%= order.mode %></td>
    <td><%= order.purchaseOrderNumber %></td>
    <td><%= link_to 'Show', [order.load, order] %></td>
    <td><%= link_to 'Edit', edit_load_order_path(order.load, order) %></td>
    <td><%= link_to 'Destroy', [order.load, order], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_load_order_path(params[:load_id]) %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', load_orders_path(@order.load) %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Deliverydate:</b>
  <%= @order.deliveryDate %>
</p>

<p>
  <b>Deliveryshift:</b>
  <%= @order.deliveryShift %>
</p>

<p>
  <b>Originname:</b>
  <%= @order.originName %>
</p>

<p>
  <b>Originaddress:</b>
  <%= @order.origin_address_id %>
</p>

<p>
  <b>Clientname:</b>
  <%= @order.clientName %>
</p>

<p>
  <b>Destinationaddress:</b>
  <%= @order.destination_address_id %>
</p>

<p>
  <b>Phonenumber:</b>
  <%= @order.phoneNumber %>
</p>

<p>
  <b>Mode:</b>
  <%= @order.mode %>
</p>

<p>
  <b>Purchaseordernumber:</b>
  <%= @order.purchaseOrderNumber %>
</p>


<%= link_to 'Edit', edit_load_order_path(@order.load, @order) %> |
<%= link_to 'Back', load_orders_path(@order.load) %>